update makefile and script for benchmark

diff --git a/test/c/Makefile b/test/c/Makefile
--- a/test/c/Makefile
+++ b/test/c/Makefile
@@ -1,7 +1,8 @@
 include ../../Makefile.config
 
 CCOMP=../../ccomp
-CCOMPFLAGS=$(CCOMPOPTS) -stdlib ../../runtime  -dasm  -relf
+CCOMPFLAGS=$(CCOMPOPTS) -stdlib ../../runtime -dc -dclight -dasm -relf
+CCOMPFLAGS_NELF=$(CCOMPOPTS) -stdlib ../../runtime -dc -dclight -dasm
 
 CFLAGS=-O1 -Wall
 
@@ -15,14 +16,19 @@ PROGS=fib integr qsort fft fftsp fftw sha1 sha3 aes almabench \
   nsieve nsievebits spectral vmach \
   bisect chomp perlin siphash24
 
-all: $(PROGS:%=%.compcert) $(PROGS:%=%.compcert.noinline)
+all: $(PROGS:%=%.compcert)
+all_nelf: $(PROGS:%=%.norm.compcert)
 
 all_s: $(PROGS:%=%.s)
 
 all_gcc: $(PROGS:%=%.gcc)
 
 %.compcert: %.c $(CCOMP)
-	-$(CCOMP) $(CCOMPFLAGS) -o $*.compcert $*.c $(LIBS)
+	$(CCOMP) $(CCOMPFLAGS) -o $*.compcert $*.c $(LIBS)
+
+%.norm.compcert: %.c $(CCOMP)
+	$(CCOMP) $(CCOMPFLAGS_NELF) -o $*.norm.compcert $*.c $(LIBS)
+
 
 %.compcert.noinline: %.c $(CCOMP)
 	$(CCOMP) $(CCOMPFLAGS) -fno-inlining -o $*.compcert.noinline $*.c $(LIBS)
@@ -31,14 +37,13 @@ all_gcc: $(PROGS:%=%.gcc)
 	$(CCOMP) $(CCOMPFLAGS) -S $*.c
 
 %.gcc: %.c
-	$(CC) $(CFLAGS) -c -o $*.gcco $*.c $(LIBS)
 	$(CC) $(CFLAGS) -o $*.gcc $*.c $(LIBS)
 
 test:
 	@for i in $(PROGS); do \
 	   if ./$$i.compcert | cmp -s - Results/$$i; \
            then echo "$$i: passed"; \
-           else echo "$$i: FAILED"; \
+           else echo "$$i: FAILED"; exit 2; \
 	   fi; \
          done
 
@@ -57,8 +62,13 @@ bench_gcc:
 
 bench:
 	@for i in $(PROGS); do \
-	   echo -n "$$i with inlining   : "; $(TIME) ./$$i.compcert; \
-	   echo -n "$$i without inlining: "; $(TIME) ./$$i.compcert.noinline; \
+	   echo -n "$$i with gcc : "; $(TIME) ./$$i.gcc; \
+         done
+	@for i in $(PROGS); do \
+	   echo -n "$$i with CompcertELF   : "; $(TIME) ./$$i.compcert; \
+         done
+	@for i in $(PROGS); do \
+	   echo -n "$$i with Vanilla Compcert  : "; $(TIME) ./$$i.norm.compcert; \
          done
 
 cminor_roundtrip:
